# Generated by Django 5.2.3 on 2025-07-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polis_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(default='sometopic'),
            preserve_default=False,
        ),
    ]
