# Generated by Django 5.2.3 on 2025-07-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polis_app', '0002_topic_description_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='text',
            field=models.CharField(default='defaulttext'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='blub'),
            preserve_default=False,
        ),
    ]
