# Generated by Django 5.2.3 on 2025-07-15 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polis_app', '0003_statement_text_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statement',
            old_name='conversation',
            new_name='topic',
        ),
    ]
